{
 "title": "HttpProxy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outbound_localhost_8086_connections_count"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_count" }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cache_hits" },
    { "expr": "cache_misses" }
   ]
  }
 ]
}