/* Generated By:JavaCC: Do not edit this line. RequestMatcherConstants.java */
package org.carapaceproxy.server.mapper.requestmatcher;

public interface RequestMatcherConstants {

  int EOF = 0;
  int ALL = 5;
  int REGEXP_DEF = 6;
  int AND = 7;
  int OR = 8;
  int NOT = 9;
  int HTTPS = 10;
  int O_BRACKET = 11;
  int C_BRACKET = 12;
  int REGEXP = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"all\"",
    "\"regexp\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"https\"",
    "\"(\"",
    "\")\"",
    "<REGEXP>",
  };

}
