{
 "title": "HttpProxy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outbound_sviluppo05_sviluppo_dna_8080_connections_count"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_count" }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_misses*100/(cache_hits+cache_misses)",
     "legendFormat": "Cache miss ratio"
    },
    {
     "expr": "cache_hits*100/(cache_hits+cache_misses)",
     "legendFormat": "Cache hit ratio"
    }
   ]
  }
 ]
}